name: ethereum-returns-feature-pipeline

# on:
#   schedule:
#     - cron: '0 * * * *'
#   workflow_dispatch:
on: push

env:
  PYTHON_VERSION: 3.9
jobs:
  feature_pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install Chrome and Chromedriver
      uses: nanasess/setup-chromedriver@v2

    - name: Set up display environment
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_feature_pipeline.txt

    - name: Execute Python workflows from bash script
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
      run: jupyter nbconvert --to notebook --execute notebooks/04_feature_pipeline.ipynb
